var offsetTop = $(window).height() * 0.1;

$("a[rel*=leanModal]").leanModal({ top : offsetTop, overlay : 0.4, closeButton: ".modal_close" });

var bioInfo = {
	'katchai-name'   	: 'Kat Chai',
	'katchavez-name'   	: 'Kat Chavez',
	'javi-name'   		: 'Javier Syquia',
	'katchai-name'   	: 'Kat Chai',
	'priscilla-name' 	: 'Priscilla Arevalo',
	'francesca-name'	: 'Francesca Gallo',
	'emilia-name'		: 'Emilia Mann',
	'nick-name'			: 'Nicholas Tomlin',
	'emilio-name'		: 'Emilio Vides-Curnen',
	'anzia-name'		: 'Anzia Anderson',
	'arjun-name'		: 'Arjun Shah',
	'tina-name'			: 'Tina Yang',
	'lorraine-name'		: 'Lorraine Li',
	'niya-name'			: 'Niya Sun',
	'tina-name'			: 'Tina Yang',
	'briana-name'		: 'Briana Das',
	'tristan-name'		: 'Tristan Harris',
	'briana-name'		: 'Briana Das',
	'tristan-name'		: 'Tristan Harris',
	'rachel-name'		: 'Rachel Risoleo',
	'kirby-name'		: 'Kirby Engelman',
	'sammy-name'		: 'Sammy Randall',
	'erica-name'		: 'Erica Silver',
	'jeremy-name'		: 'Jeremy Leary',
	'elaine-name'		: 'Elaine Lu',
	'nat-name'			: 'Nat Orlando Figeroa',
	'ruthie-name'		: 'Ruthie Ashinne',
	'reet-name'			: 'Reet Agrawal',
	'ceci-name'			: 'Cecilia Berriz',
	'xuefei-name'		: 'Xuefei Yang',
	
	'blocks-name'	: 'Blocks, Bytes and Bars',
	'interplay-name' 	: 'Interplay',

	'katchai-img'   	: 'url(../../images/2018team/chair_katChai.jpg)',
	'katchavez-img'   	: 'url(../../images/2018team/chair_katChavez.jpg)',
	'javi-img'   		: 'url(../../images/2018team/chair_javi.jpg)',
	'priscilla-img' 	: 'url(../../images/2018team/con_priscilla.jpg)',
	'francesca-img'		: 'url(../../images/2018team/con_francesca.jpg)',
	'emilia-img'		: 'url(../../images/2018team/con_emilia.jpg)',
	'nick-img'			: 'url(../../images/2018team/con_nick.jpg)',
	'emilio-img'		: 'url(../../images/2018team/con_emilio.jpg)',
	'anzia-img'			: 'url(../../images/2018team/ce_anzia.jpg)',
	'arjun-img'			: 'url(../../images/2018team/ce_arjun.jpg)',
	'tina-img'			: 'url(../../images/2018team/ce_tina.jpg)',
	'lorraine-img'		: 'url(../../images/2018team/gra_lorraine.jpg)',
	'niya-img'			: 'url(../../images/2018team/gra_niya.jpg)',
	'briana-img'		: 'url(../../images/2018team/fin_briana.jpg)',
	'tristan-img'		: 'url(../../images/2018team/fin_tristan.jpg)',
	'rachel-img'		: 'url(../../images/2018team/fin_rachel.jpg)',
	'kirby-img'			: 'url(../../images/2018team/ope_kirby.jpg)',
	'sammy-img'			: 'url(../../images/2018team/ope_sammy.jpg)',
	'erica-img'			: 'url(../../images/2018team/ope_erica.jpg)',
	'jeremy-img'		: 'url(../../images/2018team/pr_jeremy.jpg)',
	'elaine-img'		: 'url(../../images/2018team/pr_elaine.jpg)',
	'nat-img'			: 'url(../../images/2018team/pr_nat.jpg)',
	'ruthie-img'		: 'url(../../images/2018team/soc_ruthie.jpg)',
	'reet-img'			: 'url(../../images/2018team/soc_reet.jpg)',
	'ceci-img'			: 'url(../../images/2018team/web_ceci.jpg)',
	'xuefei-img'		: 'url(../../images/2018team/web_xuefei.jpg)',

	'blocks-img'	: 'url(../../images/themes/blocks.png)',
	'interplay-img' : 'url(../../images/themes/interplay.png)',

	'katchai-bio'   	: "Kathleen is a sophomore at Brown from New Jersey studying computer science-economics. She is very interested in the intersection between technology and design and how they interact in human relationships with machines. Outside of the computer lab, Kat can be spotted buying notebooks she doesn't need and hunting down her next cup of coffee.",
	'katchavez-bio'   	: "Katherine Chavez is a third-year undergraduate student at Brown, where she is studying Art History (with a focus on Latin American/Latinx art) and Visual Art (with a focus on printmaking). A native of Los Angeles, California, she is very passionate about arts education for youth of all backgrounds and increasing representation in the contemporary art and design worlds. As she artist, Kat is currently exploring oil painting and practices for natural self-healing. She has a soft spot for Ritz crackers.",
	'javi-bio'   		: "Javier is a second year student from the Philippines majoring in Graphic Design at RISD concentrating in Chemistry at Brown. He is immensly intersted in the relationships between art, design, and STEM, and hopes to find more connections between them through his studies. ",
	'priscilla-bio' 	: "Priscilla is a sophomore at Brown studying sociology and passionate about anything and all related to the Andes. She took 2 years off from school, during which she travelled to Europe and South America and hopes this travel bug will persist for years to come. After graduating, she hopes to write an ethnography on indigenous communities in South America and get involved with non-profit work in Ecuador. A native to NJ, she loves reading Julio Cortazar, listening to GroupLove and strange performance art pieces.",
	'francesca-bio'		: "Francesca began her studies at NYU’s Gallatin School of Individualized Study and is now a junior at Brown studying Urban Studies with an emphasis on community engagement and sustainability. When not in class, Francesca is likely in the dance studio as a process-centered performer and choreographer. The highlight of Francesca’s dance career took place wearing a Juicy Couture track suit last year.",
	'emilia-bio'		: "Emilia is a second year student majoring in Apparel at RISD and doing an Independent Concentration at Brown on the integration of biology, technology, and apparel.  She is excited by the new fields that are emerging between the different STEM disciplines and the arts. In her free time you can find her knitting or baking.",
	'nick-bio'			: "Raised in Nashville, Nicholas is currently a junior at Brown studying math and linguistics. He's currently working on a translation of the Communist Manifesto into emoji and can be found drinking copious amounts of bubble tea.",
	'emilio-bio'		: "Emilio is a third year student at Brown studying the architectural studies track in the History of Art and Architecture concentration, hoping to also concentrate in visual arts. Originally from Boston and a lifetime city resident, he is interested in discovering the ways that art improves urban life and the ways in which design can empower urban populations, especially those that are most marginalized. He also loves cats, plants, and the color red, and longs for the day when human hibernation becomes socially acceptable.",
	'anzia-bio'			: "Anzia is a Junior at Brown University double concentrating in Urban Studies and Visual Art. Originally from New York, she is particularly interested in the ways art and design can give rise to more equitable urban spaces. She enjoys learning how to use new tools and hanging out with her pet snake, Violet.",
	'arjun-bio'			: "Arjun is a first-year undergraduate student at RISD. He intends to major in Industrial Design. He is exceedingly excited about the relationship between computer science and industrial design and aims to understand the infinite possibilities better when the two are combined. He now suggests that you re-read this bio while imagining that Morgan Freeman is narrating.",
	'tina-bio'			: "Tina is a sophomore studying neuroscience at Brown. She is interested in how understanding neurobiology can lead to improvements in mental health awareness, treatment, and education. She loves bad puns and Atlanta sweet tea. Ask her about her dog! ",
	'lorraine-bio'		: "Lorraine is from Amoy, China. She is a Sophomore studying Graphic Design at RISD. She is interested in the intersection between computer science and design, and how graphic design influences people’s behavior. Her interest also include consuming and talking about bubble tea.",
	'niya-bio'			: "Niya Sun, right now a sophomore majoring in graphic design at RISD, approaches life with curiosity and loves to capture those poetic moments in life that're the biggest inspo for her art. Interested in how the art industry works nowadays and its over-mystification, she hopes to increase the public interest and access to art and design. ",
	'briana-bio'		: "Originally from the San Francisco Bay Area, Briana is a first-year at Brown University. She is interested in working at the intersection of human behavior and visual art with an intention of creating an independent concentration in human-centered design. A passionate doodler and outdoor explorer, she can be found backpacking with her family or raiding a local Trader Joe’s.",
	'tristan-bio'		: "Tristan is a sophomore at Brown studying Economics and Art History. He enjoys exploring how multi-disciplinary strategies can sustain value for both institutions and individuals. He is particularly interested in art that utilizes interventions into dominating systems as a means of critique. Raised in Florida, he enjoys running (but not up College Hill) and wishes that it was possible for Brown and RISD to relocate somewhere warmer during the winter. ",
	'rachel-bio'		: "Rachel is a junior studying Political Science at Brown. Originally from Washington, DC, Rachel has a passion for all things public policy and public service. She is particularly interested in how law and policy can interact with design to promote social change. Outside of class, you can find Rachel singing to herself or talking about the Tasty video she wants to recreate (though she has yet to get around to actually doing it).",
	'kirby-bio'			: "Kirby is from the lakeside bits just outside of Chicago. She is a .5 Junior concentrating in Urban Studies at Brown, exploring the intersections of design, sustainability and the built environment. Super interested in film, Kirby spends her summers exploring National Parks and other natural magic lands with her brother, creating an educational kid's tv series along the way. Outside of school and the film universe, you can find Kirby at a yoga class, singing while cooking or walking or biking or near any body of water, or buying more plants to make her home more of a jungle.",
	'sammy-bio'			: "A sophomore from Cambridge, Massachusetts, Sammy studies Public Policy at Brown because she has a corny dream to help people. She is particularly interested in sustainable, human-centered design, both in the traditional design sense (particularly urban planning!) and through law and policy. Even more so, Sammy loves any sort of cute animal (she will cry watching dog videos) and any baked good that incorporates the raspberry. ",
	'erica-bio'			: "Born in Korea and raised in Seattle, Erica is a second-year Graphic Design student at RISD. Her works focus on blurring the lines between fine art and design, where the traditional and new media intersect to create an informative yet meaningful design. She’s also passionate about artists’ role in politics. When not crying over Adobe InDesign, Erica can be spotted in Chipotle or the gym.",
	'jeremy-bio'		: "Hailing from the Golden State, Jeremy is pursuing an Independent Concentration in \"Multimedia Storytelling\" in his sophomore year at Brown. He's been described as \"a hugger,\" and practices design by stringing netted rope platforms between the branches of Redwood trees back home. He never lets push come to shove. ",
	'elaine-bio'		: "Elaine is a junior studying Industrial Design as RISD. She is a Bay Area native and is interested in how products, technology, and services affect human experience. Talk to her about driving along the coast and jamming out to Spotify's top 50!",
	'nat-bio'			: "Natasha is a junior studying History of Art and Architecture at Brown. She is a first generation immigrant and lives in New York. This is Natasha's second year working with Better World by Design. Last year, she worked on Finance and is excited to transition to PR. This year she hopes to see Better World making stronger connections with alumni entreprenurs from Brown and RISD. In her free time, you can find Natasha making mac & cheese for her friends, watching educational YouTube content, and investigating how art and design can inform socially responsible business practices.",
	'ruthie-bio'		: "Ruthie is a Habesha first year at Brown. Passionate about leading the growth of education for the betterment of society and love for design and arts she chose a BEO + Visual Arts track. At her purest, she is a cat, but a total dog person so if not on campus, she is probably in Downtown Providence looking for dogs to \"run in to\". Hit her up for some scheming or for a mystery that needs decryption.",
	'reet-bio'			: "Reet is a first year undergraduate student from India studying at Brown. She intends to concentrate in areas that will allow her to intersect her interests in art and STEM. When she's not in the art studio or the computer lab, she can be found playing board games with her friends or trying to set a new rhythm with her drum kit.",
	'ceci-bio'			: "A first year graduate student at Brown, Cecilia is studying computer science, and is particularly interested in graphics, animation and visual effects. Originally from Puerto Rico, she now enjoys roaming around the roads of Providence with the squirrels. She likes cooking but is only sometimes good at it. She also likes dinosaurs, sci-fi movies and Doritos. ",
	'xuefei-bio'		: "Xuefei is a junior in Industrial Design at RISD, interested in the intersection of art, design and technology and loves to create interesting interaction between human and machine. She is born on a snowy day in Beijing and her name means snow. She dreams of travelling around the world (extraterrestrial too, if possible), speaking all the languages (computer language too, if possible) and living in a tree house. ",


	'blocks-bio'					   : 'On the occasion of Better World’s 10th anniversary in 2017, we decided to organize a different kind of conference in aims of breaking the conversational mold. The 2017 theme, Blocks, Bytes, and Bars, used symbols to provide an alternative method of conceiving the design process. These three objects represent design’s traditional past, technological present, and aspirational future.',
	'interplay-bio'					   : 'On 2016, the theme was Interplay, defined as "the way in which two or more things have an effect on each other when they happen or exist together\". Broken down into micro, meso, and macro scale, the conference\'s theme explored design interactions and its application in the personal, public, and global level. ',

	'katchai-link'   	: 'https://www.linkedin.com/in/kathleen-chai/',
	'katchavez-link'   	: 'http://katchavez.com/',
	'javi-link'   		: 'http://javier-syquia.com/',
	'priscilla-link' 	: 'linkedin.com/in/priscilla-arevalo-206b14113',
	'francesca-link'		: 'https://www.francesca-gallo.com/',
	// 'emilia-img'		: 'url(../../images/2018team/con_emilia.jpg)',
	'nick-link'			: 'https://www.linkedin.com/in/nitomlin/',
	'emilio-link'		: 'https://www.behance.net/emilio_vid7cc3',
	// 'anzia-img'			: 'url(../../images/2018team/ce_anzia.jpg)',
	// 'arjun-img'			: 'url(../../images/2018team/ce_arjun.jpg)',
	// 'tina-img'			: 'url(../../images/2018team/ce_tina.jpg)',
	'lorraine-link'		: 'http://lorraine.li',
	// 'niya-img'			: 'url(../../images/2018team/gra_niya.jpg)',
	'briana-link'		: 'http://www.brianadas.com/',
	'tristan-link'		: 'https://www.linkedin.com/in/tristanharris1/',
	'rachel-link'		: 'https://www.linkedin.com/in/rachel-risoleo/',
	// 'kirby-img'			: 'url(../../images/2018team/ope_kirby.jpg)',
	// 'sammy-img'			: 'url(../../images/2018team/ope_sammy.jpg)',
	'erica-link'			: 'http://esilver.myportfolio.com',
	'jeremy-link'		: 'https://www.linkedin.com/in/jeremy-leary-ab65b4154/',
	'elaine-link'		: 'https://www.linkedin.com/in/eelainelu/',
	// 'nat-img'			: 'url(../../images/2018team/pr_nat.jpg)',
	'ruthie-link'		: 'https://www.linkedin.com/in/ruth-ashinne-115b0814a',
	// 'reet-img'			: 'url(../../images/2018team/soc_reet.jpg)',
	'ceci-link'			: 'https://www.behance.net/cberriz',
	'xuefei-link'		: 'https://www.xuefei-yang.com',

	'blocks-link'					   : 'http://betterworldxdesign.com/conference_2017.html',
	'interplay-link'		: 'http://www.core77.com/gallery/56525/From-Pneumatic-Inflatables-to-Designing-for-Healthcare-Better-World-by-Design-2016',
	
	
		'presenter-AlanHarlam-name'         : 'ALAN HARLAM',
	'presenter-AllenPenniman-name'      : 'ALLEN PENNIMAN',
	'presenter-AndrewMartinez-name'     : 'ANDREW MARTINEZ',
	'presenter-AndrewScanlan-name'      : 'ANDREW SCANLAN',
	'presenter-AndyLaw-name'            : 'ANDY LAW',
	'presenter-AugustLehrecke-name'     : 'AUGUST LEHRECKE',
	'presenter-AzminaAlimohd-name'      : 'AZMINA ALIMOHD',
	'presenter-BeckySlogeris-name'      : 'BECKY SLOGERIS',
	'presenter-BoriFeher-name'          : 'BORI FEHER',
	'presenter-CarlyWais-name'          : 'CARLY WAIS',
	'presenter-CarolineMcAndrews-name'  : 'CAROLINE MCANDREWS',
	'presenter-CesarHidalgo-name'       : 'CESAR HIDALGO',
	'presenter-ChrisNovello-name'       : 'CHRIS NOVELLO',
	'presenter-ChristinaAgapakis-name'  : 'CHRISTINA AGAPAKIS',
	'presenter-CraigDykers-name'        : 'CRAIG DYKERS',
	'presenter-CynthiaPoon-name'        : 'CYNTHIA POON',
	'presenter-DanaChisnel-name'        : 'DANA CHISNEL',
	'presenter-DanSheehan-name'         : 'DAN SHEEHAN',
	'presenter-DavidRojas-Leon-name'    : 'DAVID ROJAS-LEÓN',
	'presenter-DhairyaPujara-name'      : 'DHAIRYA PUJARA',
	'presenter-ElizabethWilliams-name'  : 'ELIZABETH WILLIAMS',
	'presenter-EllenSu-name'            : 'ELLEN SU',
	'presenter-EmilyHerrick-name'       : 'EMILY HERRICK',
	'presenter-EmilyKao-name'           : 'EMILY KAO',
	'presenter-GenaWirth-name'          : 'GENA WIRTH',
	'presenter-HannahChung-name'        : 'HANNAH CHUNG',
	'presenter-IanGonsher-name'         : 'IAN GONSHER',
	'presenter-IanAldenRussell-name'    : 'IAN ALDEN RUSSEL',
	'presenter-IlonaGaynor-name'        : 'ILONA GAYNOR',
	'presenter-ImranHafiz-name'         : 'IMRAN HAFIZ',
	'presenter-IngridBurrington-name'   : 'INGRID BURRINGTON',
	'presenter-JaminWarren-name'        : 'JAMIN WARREN',
	'presenter-JeremyJoachim-name'      : 'JEREMY JOACHIM',
	'presenter-JessSuttner-name'        : 'JESS SUTTNER',
	'presenter-JuhanSonin-name'         : 'JUHAN SONIN',
	'presenter-KatieCafaro-name'        : 'KATIE CAFARO',
	'presenter-KaylaIngram-name'        : 'KAYLA INGRAM',
	'presenter-KellanHays-name'         : 'KELLEN HAYS',
	'presenter-KenjiEndo-name'          : 'KENJI ENDO',
	'presenter-KursatOzenc-name'        : 'KURSAT OZENC',
	'presenter-LaurenGardner-name'      : 'LAUREN GARDNER',
	'presenter-LeahChung-name'          : 'LEAH CHUNG',
	'presenter-LelandKirshen-name'      : 'LELAND KIRSHEN',
	'presenter-LeslieFontana-name'      : 'LESLIE FONTANA',
	'presenter-LeviBedall-name'         : 'LEVI BEDALL',
	'presenter-LisaRaiola-name'         : 'LISA RAIOLA',
	'presenter-ManoloAmpudia-name'      : 'MANOLO AMPUDIA',
	'presenter-MariaNavia-name'         : 'MARIA NAVIA',
	'presenter-MattMuller-name'         : 'MATT MULLER',
	'presenter-MaxFowler-name'          : 'MAX FOWLER',
	'presenter-MeganKelly-name'         : 'MEGAN KELLY',
	'presenter-MikeWeikert-name'        : 'MIKE WEIKERT',
	'presenter-MikhaelaDietch-name'     : 'MIKHAELA DIETCH',
	'presenter-NateStorring-name'       : 'NATE STORRING',
	'presenter-OlgaElizarova-name'      : 'OLGA ELIZAROVA',
	'presenter-PhilRoss-name'           : 'PHIL ROSS',
	'presenter-RinatSherzer-name'       : 'RINAT SHERZER',
	'presenter-RobertArens-name'        : 'ROBERT ARENS',
	'presenter-RyanMurphy-name'         : 'RYAN MURPHY',
	'presenter-SabrinaDorsainvil-name'  : 'SABRINA DORSAINVIL',
	'presenter-SamanthaDempsey-name'    : 'SAMANTHA DEMPSEY',
	'presenter-SaraMamo-name'           : 'SARA MAMO',
	'presenter-SarahRoss-name'          : 'SARAH ROSS',
	'presenter-StefanoBloch-name'       : 'STEFANO BLOCH',
	'presenter-StephanieCaress-name'    : 'STEPHANIE CARESS',
	'presenter-TadHirsch-name'          : 'TAD HIRSCH',
	'presenter-TaylorAlarcon-name'      : 'TAYLOR ALARCON',
	'presenter-TegaBrain-name'          : 'TEGA BRAIN',
	'presenter-ThatcherBean-name'       : 'THATCHER BEAN',
	'presenter-ThomasThwaites-name'     : 'THOMAS THWAITES',
	'presenter-VirgilWong-name'         : 'VIRGIL WONG',

	'presenter-AmandaPhingbodhipakkiya-name': 'Amanda Phingbodhipakkiya',
	'presenter-AnnuMatthew-name'        : 'Annu Matthew',
	'presenter-AlexandraGinsberg-name'  : 'Alexandra Ginsberg',
	'presenter-BarbaraWeinreich-name'   : 'Barbara Weinreich',
	'presenter-BethRattner-name'		: 'Beth Rattner',

	'presenter-AlanHarlam-img'         : 'url(../../images/presenters/AlanHarlam.jpg)',
	'presenter-AllenPenniman-img'      : 'url(../../images/presenters/AllenPenniman.jpg)',
	'presenter-AndrewScanlan-img'      : 'url(../../images/presenters2017/AndrewScanlan.jpg)',
	'presenter-AndrewMartinez-img'     : 'url(../../images/presenters/AndrewMartinez.jpg)',
	'presenter-AndyLaw-img'            : 'url(../../images/presenters/AndyLaw.jpg)',
	'presenter-AugustLehrecke-img'     : 'url(../../images/presenters/AugustLehrecke.jpg)',
	'presenter-AzminaAlimohd-img'      : 'url(../../images/presenters/AzminaAlimohd.jpg)',
	'presenter-BeckySlogeris-img'      : 'url(../../images/presenters/BeckySlogeris.jpg)',
	'presenter-BoriFeher-img'          : 'url(../../images/presenters/BoriFeher.jpg)',
	'presenter-CarlyWais-img'          : 'url(../../images/presenters/CarlyWais.jpg)',
	'presenter-CarolineMcAndrews-img'  : 'url(../../images/presenters/CarolineMcAndrews.jpg)',
	'presenter-CesarHidalgo-img'       : 'url(../../images/presenters/CesarHidalgo.jpg)',
	'presenter-ChrisNovello-img'       : 'url(../../images/presenters/ChrisNovello.jpg)',
	'presenter-ChristinaAgapakis-img'  : 'url(../../images/presenters/ChristinaAgapakis.jpg)',
	'presenter-CraigDykers-img'        : 'url(../../images/presenters/CraigDykers.jpg)',
	'presenter-CynthiaPoon-img'        : 'url(../../images/presenters/CynthiaPoon.jpg)',
	'presenter-DanaChisnel-img'        : 'url(../../images/presenters/DanaChisnel.jpg)',
	'presenter-DanSheehan-img'         : 'url(../../images/presenters/DanSheehan.jpg)',
	'presenter-DavidRojas-Leon-img'    : 'url(../../images/presenters/DavidRojas-Leon.jpg)',
	'presenter-DhairyaPujara-img'      : 'url(../../images/presenters/DhairyaPujara.jpg)',
	'presenter-ElizabethWilliams-img'  : 'url(../../images/presenters/ElizabethWilliams.jpg)',
	'presenter-EllenSu-img'            : 'url(../../images/presenters/EllenSu.jpg)',
	'presenter-EmilyHerrick-img'       : 'url(../../images/presenters/EmilyHerrick.jpg)',
	'presenter-EmilyKao-img'           : 'url(../../images/presenters/EmilyKao.jpg)',
	'presenter-GenaWirth-img'          : 'url(../../images/presenters/GenaWirth.jpg)',
	'presenter-HannahChung-img'        : 'url(../../images/presenters/HannahChung.jpg)',
	'presenter-IanGonsher-img'         : 'url(../../images/presenters/IanGonsher.jpg)',
	'presenter-IanAldenRussell-img'    : 'url(../../images/presenters/IanAldenRussell.jpg)',
	'presenter-IlonaGaynor-img'        : 'url(../../images/presenters/IlonaGaynor.jpg)',
	'presenter-ImranHafiz-img'         : 'url(../../images/presenters/ImranHafiz.jpg)',
	'presenter-IngridBurrington-img'   : 'url(../../images/presenters/IngridBurrington.jpg)',
	'presenter-JaminWarren-img'        : 'url(../../images/presenters/JaminWarren.jpg)',
	'presenter-JeremyJoachim-img'      : 'url(../../images/presenters/JeremyJoachim.jpg)',
	'presenter-JessSuttner-img'        : 'url(../../images/presenters/JessSuttner.jpg)',
	'presenter-JuhanSonin-img'         : 'url(../../images/presenters/JuhanSonin.jpg)',
	'presenter-KatieCafaro-img'        : 'url(../../images/presenters/KatieCafaro.jpg)',
	'presenter-KaylaIngram-img'        : 'url(../../images/presenters/KaylaIngram.jpg)',
	'presenter-KellanHays-img'         : 'url(../../images/presenters/KellanHays.jpg)',
	'presenter-KenjiEndo-img'          : 'url(../../images/presenters/KenjiEndo.jpg)',
	'presenter-KursatOzenc-img'        : 'url(../../images/presenters/KursatOzenc.jpg)',
	'presenter-LaurenGardner-img'      : 'url(../../images/presenters/LaurenGardner.jpg)',
	'presenter-LeahChung-img'          : 'url(../../images/presenters/LeahChung.jpg)',
	'presenter-LelandKirshen-img'      : 'url(../../images/presenters/LelandKirshen.jpg)',
	'presenter-LeslieFontana-img'      : 'url(../../images/presenters/LeslieFontana.jpg)',
	'presenter-LeviBedall-img'         : 'url(../../images/presenters/LeviBedall.jpg)',
	'presenter-LisaRaiola-img'         : 'url(../../images/presenters/LisaRaiola.jpg)',
	'presenter-ManoloAmpudia-img'      : 'url(../../images/presenters/ManoloAmpudia.jpg)',
	'presenter-MariaNavia-img'         : 'url(../../images/presenters/MariaNavia.jpg)',
	'presenter-MattMuller-img'         : 'url(../../images/presenters/MattMuller.jpg)',
	'presenter-MaxFowler-img'          : 'url(../../images/presenters/MaxFowler.jpg)',
	'presenter-MeganKelly-img'         : 'url(../../images/presenters/MeganKelly.jpg)',
	'presenter-MikeWeikert-img'        : 'url(../../images/presenters/MikeWeikert.jpg)',
	'presenter-MikhaelaDietch-img'     : 'url(../../images/presenters/MikhaelaDietch.jpg)',
	'presenter-NateStorring-img'       : 'url(../../images/presenters/NateStorring.jpg)',
	'presenter-OlgaElizarova-img'      : 'url(../../images/presenters/OlgaElizarova.jpg)',
	'presenter-PhilRoss-img'           : 'url(../../images/presenters/PhilRoss.jpg)',
	'presenter-RinatSherzer-img'       : 'url(../../images/presenters/RinatSherzer.jpg)',
	'presenter-RobertArens-img'        : 'url(../../images/presenters/RobertArens.jpg)',
	'presenter-RyanMurphy-img'         : 'url(../../images/presenters/RyanMurphy.jpg)',
	'presenter-SabrinaDorsainvil-img'  : 'url(../../images/presenters/SabrinaDorsainvil.jpg)',
	'presenter-SamanthaDempsey-img'    : 'url(../../images/presenters/SamanthaDempsey.jpg)',
	'presenter-SaraMamo-img'           : 'url(../../images/presenters/SaraMamo.jpg)',
	'presenter-SarahRoss-img'          : 'url(../../images/presenters/SarahRoss.jpg)',
	'presenter-StefanoBloch-img'       : 'url(../../images/presenters/StefanoBloch.jpg)',
	'presenter-StephanieCaress-img'    : 'url(../../images/presenters/StephanieCaress.jpg)',
	'presenter-TadHirsch-img'          : 'url(../../images/presenters/TadHirsch.jpg)',
	'presenter-TaylorAlarcon-img'      : 'url(../../images/presenters/TaylorAlarcon.jpg)',
	'presenter-TegaBrain-img'          : 'url(../../images/presenters/TegaBrain.jpg)',
	'presenter-ThatcherBean-img'       : 'url(../../images/presenters/ThatcherBean.jpg)',
	'presenter-ThomasThwaites-img'     : 'url(../../images/presenters/ThomasThwaites.jpg)',
	'presenter-VirgilWong-img'         : 'url(../../images/presenters/VirgilWong.jpg)',

	'presenter-AmandaPhingbodhipakkiya-img' : 'url(../../images/presenters2017/AmandaPhingbodhipakkiya.jpg)',
	'presenter-AnnuMatthew-img' 	   : 'url(../../images/presenters2017/Annu.jpg)',
	'presenter-AlexandraGinsberg-img'  : 'url(../../images/presenters2017/AlexandraGinsberg.jpg)',
	'presenter-BarbaraWeinreich-img'   : 'url(../../images/presenters2017/BarbaraWeinreich.jpg)',
	'presenter-BethRattner-img'		   : 'url(../../images/presenters2017/BethRattner.jpg)',

	'presenter-AlanHarlam-bio'         : "Alan is the Director of Social Innovation at Brown's Swearer Center. The Social Innovation Initiative (SII) reaches hundreds of students and alumni each year with programs that support students who are learning about social innovation, launching their own social impact ventures, and crafting lives and careers of impact.  Outside of work, Alan serves on the boards of Social Enterprise Greenhouse, City Year and Eye to Eye.",
	'presenter-AllenPenniman-bio'      : "Allen Penniman is a principal planner for the City of Providence and founding director of Street Ops, a Boston-based tactical urbanism collective. Previously, Allen managed master plans for Sasaki Associates. Operating at the intersection of urban design and community economic development, Allen's work uses the power of planning and design policy to foster equitable redevelopment in urban communities. Currently, Allen is immersed in a highway-to-boulevard project in Providence, where he also spearheads a \"living alleys\" program and leads area plans for post-industrial neighborhoods.",
	'presenter-AndrewScanlan-bio'      : 'Andrew is a Senior in the Combined A.B./Sc.B Program, concentrating in Philosophy and Mechanical Engineering.  Beyond classes, Andrew devotes much of his time to Design for America, through which he’s led projects on medication noncompliance and homelessness and worked on stormwater runoff.  In his spare time, Andrew enjoys making and experiencing music and exploring quiet natural spaces, like those around his hometown of Bradford, Pennsylvania.',
	'presenter-AndrewScanlan-bio'      : 'Andrew is a Senior in the Combined A.B./Sc.B Program, concentrating in Philosophy and Mechanical Engineering.  Beyond classes, Andrew devotes much of his time to Design for America, through which he’s led projects on medication noncompliance and homelessness and worked on stormwater runoff.  In his spare time, Andrew enjoys making and experiencing music and exploring quiet natural spaces, like those around his hometown of Bradford, Pennsylvania.',
	'presenter-AndrewMartinez-bio'     : "Andrew Martinez is the Archivist for the Rhode Island School of Design, a position he has held since 1997, when he first came to establish this unique collection for RISD.  He has written about various aspects of RISD's history and coedited the anthology Infinite Radius: Founding Rhode Island School of Design.  Andrew has previously written about the 1913 Armory Show at the Art Institute of Chicago and is currently at work on a publication about Alexander Dorner, Director of the RISD Museum from 1938-1941.",
	'presenter-AugustLehrecke-bio'     : 'August Lehrecke is a Furniture Design graduate from RISD and co-founder of Pneuhaus.  At Pneuhaus, August’s role mainly lies in the fields of spatial and computational design. Interested in space filling geometries and crystalline structures, he looks for ways of scaling these micro phenomena into a human scale. Experienced with a wide range of materials and fabrication techniques, he facilitates the transition from the digital model to the production process.',
	'presenter-AzminaAlimohd-bio'      : 'Azmina Alimohd is a native Chicagoan and graduated from the University of Illinois at Urbana-Champaign with a BA in Urban Planning and a BS in Earth Systems, Environment, and Society. During her studies, she interned at several initiatives, working to create and promote sustainable business practices in Illinois. Azmina completed a post-graduate certificate in Sustainable Urban Design at Archeworks, where she partnered with Growing Power, a local urban farm, to design educational and way-finding materials and farm tour experiences.',
	'presenter-BeckySlogeris-bio'      : "Becky Slogeris is a Social Design Associate at the Center for Social Design at Maryland Institute College of Art (MICA). She runs the Center's Education and Youth Initiative, which uses social design to explore solutions to the most pressing needs of young people in and out of the classroom. Her work is focused on designing project-based curricula and tools to empower students to create change in their communities. Past partners have included Baltimore City Public Schools, Baltimore Urban Debate League, Carrot New York, USDA, FEMA, Maryland Coalition Against Sexual Assault, Real Food Farm, Sandy Hook Promise, Teach for All, Teach for America, and the White House's My Brother's Keeper Initiative. She has a BFA in graphic design and an MA in Social Design from MICA.",
	'presenter-BoriFeher-bio'          : 'Bori Feher is an architect and researcher focused on social design and resilience. She is the co-founder and Program Director of MOME EcoLab in Budapest. At the Lab she facilitates students in social, eco and humanitarian design projects, collaborating with NGOs like UNHCR. Their long-term rural development project Cloudfactory aims to empower kids living in extreme poverty with the tools of design. <br /><br />Previously Bori has worked at TEK Architects, Post Sandy Hurricane Reconstruction Project at Architecture for Humanity New York, and was a fellow at DesigNYC. She received MAs in Architectural Design and Design Management from MOME.',
	'presenter-CarlyWais-bio'          : 'Carly Wais grew up in Baltimore. They earned a B.S. in Earth Systems from Stanford University, interned with the Anti-Eviction Mapping Project in San Francisco, and then returned home to continue working towards housing justice back in Baltimore. Last year Carly completed their masters in Social Design at Maryland Institute College of Art. They were extremely fortunate to have the opportunity to co-design with returning citizens in Baltimore through the <a target="_blank" href="http://www.governing.com/cityaccelerator/about">City Accelerator grant</a>. Their thesis work focused on creating new platforms for people coming back from prison and jail to connect with resources and each other. Though Carly’s thesis is now complete, the work is ongoing and they can’t wait to talk to you about it!',
	'presenter-CarolineMcAndrews-bio'  : 'Caroline McAndrews is a research & social strategist with over 15 years of experience in assessment, writing and program development.  She’s worked with academics, activists, business and community members to explore questions such as how to develop the next generation of leadership, engage customers in social change, and build a systems approach to service work. She holds an MFA in Design for Social Innovation from the School of Visual Arts, and a BA in Urban Studies with a focus in architecture from Stanford University. The author of several reports, including What Works: Developing Successful Multigenerational Leadership, Caroline consults for Building Movement Project, where she most recently served as the Director of Research and Documentation.',
	'presenter-CesarHidalgo-bio'       : "César A. Hidalgo leads the Macro Connections group at The MIT Media Lab and is an Associate Professor of Media Arts and Sciences at MIT. Hidalgo's work focuses on understanding the intelligence of systems, with a particular focus on economic development and the creation of data visualization engines. Hidalgo is the author of Why Information Grows, the co-author of The Atlas of Economic Complexity and a co-founder of Datawheel LLC. His academic publications have been cited more than 7,000 times.",
	'presenter-ChrisNovello-bio'       : 'Chris Novello graduated from Brown University and has worked as adjunct faculty at RISD and as a visiting scholar at Brown University. He founded Illuica, where he designs and builds patchbay instruments for connecting computer programs. He also worked on the speculative design project, Bitelabs, which grows meat from celebrity tissue samples to make artisanal salami and on Genecoin, a project that samples DNA, turns it into data, and stores it in the Bitcoin network.',
	'presenter-ChristinaAgapakis-bio'  : 'Christina Agapakis is creative director of Ginkgo Bioworks, a biological design company growing cultured products for partners across many industries. Her work brings together biologists, engineers, designers, artists, and social scientists to explore the future of biotechnology. During her PhD at Harvard, she worked on producing hydrogen fuel in bacteria and making photosynthetic animals. She has taught designers at the Art Center College of Design and biomolecular engineers at UCLA, and she once made cheese using bacteria from the human body.',
	'presenter-CraigDykers-bio'        : 'Craig Dykers,one of the Founding Partners of Snøhetta, has led many prominent projects internationally, including the Alexandria Library in Egypt, the Norwegian National Opera and Ballet in Norway, the National September 11 Memorial Museum Pavilion in New York City, and the San Francisco MOMA Expansion. He’s interested in design as a promoter of social and physical well-being. Craig is currently leading the design of the new Times Square Reconstruction in New York City.',
	'presenter-CynthiaPoon-bio'        : "Cynthia Poon (RISD ID ‘13) is a toy designer who works/plays alongside Maeve Jopson as co-founder of Increment, a social venture promoting inclusion through play and collaboration between occupational therapists, teachers, parents, and kids through universal and human-centered design. Increment was recently awarded the 2016 Parents' Choice Gold Award, has been recognized by Core77, Ashoka Changemakers, and was named a 2015 Mass Challenge Finalist.",
	'presenter-DanaChisnel-bio'        : 'Dana E. Chisnell, co-director of the Center for Civic Design, is an elections nerd who researches design in elections. She has trained thousands of election officials on plain language and usability. She’s the lead on a project to develop a series of Field Guides To Ensuring Voter Intent. The Field Guides are designed to be quick, easy, and accessible help for local election officials to do the best possible design.',
	'presenter-DanSheehan-bio'         : 'A simple root vegetable may sound like an unlikely inspiration for a business plan, but for Daniel Sheehan, it was a catalyst for clarity. Pie represents three things that we believe are important in quality baked goods. First, pie is fresh. It can use the seasonal ingredients that Rhode Islanders are so skilled at growing and producing throughout each year. Second, pie is simple. This simplicity demands that attention is paid to quality. Third, pie is community. It is made to be shared and, most importantly, made with love.',
	'presenter-DavidRojas-Leon-bio'    : 'David Rojas-León is a Colombian graphic designer with degrees from Universidad Jorge Tadeo Lozano in Bogotá and the MFA Design for Social Innovation at School of Visual Arts in New York. His experience in NYC and Colombia includes interning for the Digital Team at Hillary for America, participating in Earth to Paris 2015 as Visual Design Fellow, co-producing Priya Shakti Augmented Reality Art Exhibition and working for Casa Editorial El Tiempo and the City Hall of Bogotá. He engages in activism for gender equity, LGBT rights, and open-source software.',
	'presenter-DhairyaPujara-bio'      : 'Dhairya Pujara, Founder and CEO for Ycenter is responsible for building a global ecosystem involving corporations, universities and NGOs for creating community solutions, with projects in Mozambique and India. He teaches entrepreneurship programs using Human Centered Design process in USA and Kenya and lectures worldwide. Dhairya is also an advisory board member for the European Commission program Latin American Social Innovation network. In 2015, American Immigration granted him a special category work visa for "an individual of extra-ordinary abilities”.',
	'presenter-ElizabethWilliams-bio'  : "Elizabeth Williams is a curator of decorative arts and design at the Rhode Island School of Design Museum.  She oversees the museum’s collection of American and European decorative arts and RISD's teaching and community engagement. Her work primarily focuses on exhibitions, publications, and creating venues for participation. Previously, she worked as the assistant curator of decorative arts at the Los Angeles Country Museum of Art. Elizabeth's expertise is in eighteenth and nineteenth century silver.",
	'presenter-EllenSu-bio'            : 'Ellen Su is the CEO and a co-founder of Wellinks, a medical device company, where she works on product design, graphic design, branding, and UI/UX. Wellinks is developing a compliance monitor for scoliosis braces that helps kids, parents, and clinicians keep track of treatment and avoid surgery. Ellen is interested in how people interact with technology, particularly the role it plays in helping us form and break habits.',
	'presenter-EmilyHerrick-bio'       : 'Emily Herrick grew up around Chicago and graduated from Illinois State University with double degrees in Graphic Design and Arts Technology, which she paired with a minor in Civic Engagement & Social Responsibility. She started her career as an interior book designer at Penguin Random House. Before then, Emily worked in visual identity for a number of socially-minded institutions in Chicago, including Moira & Company. She’s currently a Communications Designer at Reboot, where she produces visual materials for clients in the international development sector.',
	'presenter-EmilyKao-bio'           : 'A RISD senior in industrial design, Emily is founder of the <a target="_blank" href="http://www.facebook.com/risdidsa">RISD IDSA Student Chapter</a> and is passionate about helping the student community explore their career options by connecting with professionals. As a designer/observer/conversationalist, she is interested in creating spaces that are functional, educational, and engaging. Additionally, she is an advocate for collaborative work. So if you strike up conversation with her and would be interested in creating something bonkers, feel free to email her!',
	'presenter-GenaWirth-bio'          : 'Gena is the Design Principal at SCAPE. Trained in landscape architecture, urban planning, and horticulture, Gena draws from her interdisciplinary training to create ecologically rich and culturally relevant landscapes from the infrastructural scale to the site level. She was the Project Manager for SCAPE’s Rebuild By Design proposal, Living Breakwaters, a climate change resiliency strategy for the South Shore of Staten Island that was selected for 60M of implementation funding.',
	'presenter-HannahChung-bio'        : 'Hannah Chung graduated from Northwestern University in Mechanical Engineering. She is the Co-founder and CCO of Sproutel and the creator of Jerry the Bear, a platform to engage children in play-based healthcare education. The White House and President Obama recognized Sproutel as one of 32 companies representing diversity in tech, while Hannah was recognized as one of 50 “honored makers”. Before Sproutel, Hannah co-founded Design for America, a national student organization that helps students solve local social problems through design.',
	'presenter-IanGonsher-bio'         : 'Ian Gonsher is a Lecturer in the School of Engineering at Brown University, where his teaching and research focus on design process and creative practice across disciplines. Ian studied Art History and Industrial Design at the University of Kansas, and also holds an MFA in Furniture Design from the Rhode Island School of Design.',
	'presenter-IanGonsher-bio'         : 'Ian Gonsher is a Lecturer in the School of Engineering at Brown University, where his teaching and research focus on design process and creative practice across disciplines. Ian studied Art History and Industrial Design at the University of Kansas, and also holds an MFA in Furniture Design from the Rhode Island School of Design.',
	'presenter-IanAldenRussell-bio'    : 'Ian Alden Russell is an international curator based in Providence, Rhode Island. Currently the Curator of Brown University’s David Winton Bell Gallery, he previously held the post of Professor of Contemporary Art and Curatorial Practice at Koç University in Istanbul and has held major fellowships at Brown University, University of Notre Dame, and University College Dublin. His curatorial work has been hosted internationally  by Artpace, Chinese University of Hong Kong, Fire Station Artists’ Studios, Koç University, Ormston House, Irish Museum of Modern Art, Jockey Club Creative Arts Centre, the Museum of Innocence, and the National College of Art & Design. His writings have been published by various publications including Cambridge University Press, Cittadellarte, and deCordova Museum & Sculpture Park. Born in Richmond, Virginia and educated in Ireland, he holds a Ph.D. in History from Trinity College Dublin.',
	'presenter-ImranHafiz-bio'         : 'Imran Hafiz is an author, futurist and filmmaker based in Brooklyn. With a global history and accompanying international network, Imran leveraged his unique experiences as an American Muslim in post-9/11 South to write The American Muslim Teenager’s Handbook, which led him to consulting work for US Dept. of State, DHS and other governmental agencies. He is currently working as an AP/Researcher for VICE, where he was part of an Emmy-award winning HBO team and the youngest TV AP for MOTHERBOARD.',
	'presenter-IngridBurrington-bio'   : "Ingrid Burrington writes, makes maps, and tells jokes about places, politics, and the weird feelings people have about both. She's an artist-in-residence at the Data and Society Research Institute and the author of Networks of New York: An Illustrated Field Guide to Urban Internet Infrastructure.",
	'presenter-JaminWarren-bio'        : "Jamin Warren is Co-Founder and Chief Executive of videogame arts and culture company Kill Screen. He was formerly a culture reporter for the Wall Street Journal and is the host of the PBS web series Game/Show. He serves as an advisor to MoMA's department of Architecture and Design. Warren has co-hosted Versions, a virtual reality conference at the New Museum. Warren graduated from Harvard in 2004. He has been featured in the New Yorker, New York Times, Paris Review and frequently contributes to NPR, and has spoken at SXSW, the New York Film Festival, XOXO. Warren graduated from Harvard in 2004.",
	'presenter-JeremyJoachim-bio'      : "Jeremy is a senior undergraduate student at Brown concentrating in Mechanical Engineering with a focus in design and communication. Project leader of Brown STEAM, Jeremy is interested in bringing in knowledge of how things work (and don't work) to create solutions that address why things work (and don't work). Jeremy is inspired by work that's interdisciplinary across fields we've been taught were never supposed to harmonize. He's currently into robots, VR/AR, meme theory, beatboxing, and playing the ukulele.",
	'presenter-JessSuttner-bio'        : 'Jess Suttner is an illustrator and designer born and raised in Chicago, educated at California College of the Arts in the Bay Area and currently based in Brooklyn, NY. He gains inspiration from all things nautical, musical and well lit. Feel free to contact him with any projects, collaborations, ice cream offerings, or to just say hey.',
	'presenter-JuhanSonin-bio'         : 'Juhan Sonin specializes in software design and system engineering. He is the Director of Involution Studios. His work has been recognized by the New York Times, Newsweek, BBC International, Billboard Magazine, WIRED, and National Public Radio . Juhan has spent time at Apple, the National Center for Supercomputing Applications, Massachusetts Institute of Technology and MITRE. He currently lectures on design and engineering at MIT.',
	'presenter-KatieCafaro-bio'        : 'Katherine is a Senior in Illustration at RISD with a growing interest in Design and Architecture. She one day aspires to be a published children’s book Illustrator, and loves working with oil paint.  Besides Art and Design, her other interests include hiking, reading, and cooking.',
	'presenter-KaylaIngram-bio'        : "Kayla Ingram is a recent graduate of the M.A. Social Design program at the Maryland Institute College of Art. Ingram is interested in unearthing new ways to advance the Black and Brown communities through design. She is currently serving Black and Brown community in Baltimore and beyond by providing graphic design services and solutions for Black and Brown led grassroots/community organizations and entrepreneurs whose work combats the imperialist, white supremacist, capitalist, patriarchal culture in which we live.",
	'presenter-KellanHays-bio'         : 'Kellan has over 12 years of experience as an international and national program manager for organizations working on conservation, education, and advocacy. Working for organizations as diverse as the Jane Goodall Institute and Autodesk, she has always been passionate about using her skills to protect people and the planet.',
	'presenter-KenjiEndo-bio'          : 'Kenji is a junior undergraduate student at Brown University concentrating in Computer Science, with interests in computer graphics, animation, sculpture, and architecture. President of Brown STEAM, Kenji also helps lead the organization’s computer science branch, C+STEAM, which focuses on the ways computer science may intersect with visual art and the humanities, in fields such as VR, graphics, and data visualization. On campus, Kenji also works for the Brown Science Center’s exhibits team and writes for The Blognonian.',
	'presenter-KursatOzenc-bio'        : 'F. Kursat Ozenc is a senior user experience designer at SAP Labs, Palo Alto. He designs software products and helps teams innovate using design thinking methods. Kursat teaches interaction design at Stanford’s d.school and leads design workshops as a part of the Legal Design Lab at Stanford Law School. He holds a Ph.D. in Design from Carnegie Mellon.',
	'presenter-LaurenGardner-bio'      : 'Lauren Gardner is originally from Houston and went to college at American University, where she pursued a degree in IR with minors in Graphic Design and Communications. After graduation, she moved to India for a year to work for the Alliance for Global Education. She joined the World Bank upon her return, where she worked on education research in Pakistan and Zambia. Lauren came to DSI to better merge her love of design and international development with her concern for social justice.',
	'presenter-LeahChung-bio'          : 'Leah Chung (RISD ID ‘14) is a social designer who works at the intersection of design and public policy. She has focused on social impact projects ranging from developing a neonatal pulse oximeter for low-income countries, to founding the RISD Global Initiative. As a 2013 RISD Maharam Fellow, she conducted ethnographic research on the misrepresentation of “Africa" in western media in Uganda. Leah is a guest lecturer at MIT and currently works at the U.S. Agency For International Development.',
	'presenter-LelandKirshen-bio'      : 'Originally from Massachusetts, Leland is currently a Senior at Brown concentrating in Mechanical Engineering.  Since discovering human-centered design and Design for America in the Spring of his sophomore year, he has been a part of two DFA teams aimed at addressing problems in the Providence community.  Outside of DFA, Leland is a first-year advisor and enjoys playing recreational sports.',
	'presenter-LeslieFontana-bio'      : 'Leslie Fontana received her BFA in 1982 from Carnegie Mellon University and her Bachelor of Science in Industrial Design from the University of the Arts. She also studied at the Domus Academy in Milan Italy. Through her consulting practice, les&more, Leslie designs for a variety of companies, offering product and system solutions. She has received awards from the Juvenile Products Manufacturers Association, The Consumer Product Safety Commission, and the Industrial Design Society of America, and the Frazier Award for Excellence in Teaching from RISD, where she is a Professor in the Industrial Design Department. Her current research is on aging and inclusive design solutions.',
	'presenter-LeviBedall-bio'         : 'Levi Bedall is a spatial designer and co-founder of Pneuhaus--a collective exploring human perception of space and temporary building technologies. Pneuhaus has fabricated 13 installations since its founding in 2014, and is currently exploring ideas of color, module building blocks, and multi-dimensional play-spaces.',
	'presenter-LisaRaiola-bio'         : "Hope & Main is Rhode Island’s first food business incubator. It's vision is to find a way to assist local entrepreneurs to jump-start early-stage food companies by providing low cost, low risk access to shared-use commercial kitchens and other industry-specific technical resources. Today Hope & Main helps to grow the local food economy by creating a community of support for food entrepreneurs and cultivating an environment where emerging culinary startups can test, create, scale and thrive. <br /><br />Lisa has more than has more than 30 years of experience in program development and advancement at non-profit organizations in healthcare and higher education with a special focus on distributive justice, social responsibility and economic development.",
	'presenter-ManoloAmpudia-bio'      : "Manolo Ampudia, born and raised in Mexico City, studied Industrial Design, and holds a MFA in Design for Social Innovation from the School of Visual Arts. He is a co-founder of Suhab, a sustainable design studio, which facilitates sustainable habit building and works with artisans communities in Mexico and Nicaragua designing services that build self-sustaining local economies. He also serves on the advisory board for the Institute for Public Architecture.",
	'presenter-MariaNavia-bio'         : "Maria Paula Navia earned an MBA in Design Strategy from the California College of the Arts and holds an Industrial Design degree, and dual minors in Entrepreneurship and Textile Design from Universidad de los Andes at Bogotá in her native country of Colombia. Her experiences meet at the intersection of design, innovation and social impact. At Be Girl, she supports the development of awarding-winning products and services that sustainably empower women.",
	'presenter-MattMuller-bio'         : "Pneuhaus is a design collective working within the fields of spatial design, temporary structures, and contemporary art to create large-scale immersive environments that relate to human scale. As architects, designers and artists, Pneuhaus weaves a discourse around the built environment.",
	'presenter-MaxFowler-bio'          : "Max Fowler is a programmer and artist currently based in New York City. Some of his recent projects have explored the ways that maps conceptualize space, expressive analysis of text message history and how to use a twitter bot to take out the trash. He is interested in speculative startups, generative systems, and the ways we use technology to decide what to read. He is a co-founder of Computer Lab, a digital consultancy, and a recent participant in the School For Poetic Computation.",
	'presenter-MeganKelly-bio'         : "Food Recovery Network is the largest student movement against food waste and hunger in America and have recovered and donated more than 1.4 million pounds of food that otherwise would have gone to waste. That's more than 1.2 million meals that's gone to those in need. Megan is a member of the Brown University FRN chapter.",
	'presenter-MikeWeikert-bio'        : "Mike Weikert is founding director of the Center for Social Design and Master of Arts in Social Design at Maryland Institute College of Art (MICA). In 2011, he was nominated for the Cooper-Hewitt National Design Award and in 2014, received the Ashoka U-Cordes Innovation Award recognizing his innovative work in design education. He also serves as a Network Representative to the Clinton Global Initiative University and is a member of the Winterhouse Design Education & Social Change Symposium Founders Circle. Previously, he served as partner/creative director at Atlanta-based Iconologic, and as a design consultant to the International Olympic Committee.",
	'presenter-MikhaelaDietch-bio'     : 'Mikhaela studies engineering with a concentration in Art + Technology at Olin College. She chose a degree in engineering to become conversant in the many vocabularies, languages, and platforms of contemporary technology. This literacy enables her to integrate technical awareness with artistic exploration and use her knowledge to engage in meaningful critique. She was also an intern at Autodesk this past summer.',
	'presenter-NateStorring-bio'       : 'Nate Storring is a writer, curator and designer with a focus on interpreting architecture, city planning, and urban issues for a general audience. He has helped produce multiple exhibitions at Urbanspace Gallery (Toronto, ON), the Chicago Architecture Foundation, and the Boston Society of Architects BSA Space. Currently, he works at Project for Public Spaces, writing regular articles for their blog, and conducting research about innovation, governance and placemaking.',
	'presenter-OlgaElizarova-bio'      : 'Olga is a dentist, healthcare analyst, behavior change designer and entrepreneur. After obtaining a public health degree at Brown University, she joined Mad*Pow, a human-centered design consultancy, to work in the digital health space as Behavior Change Designer. Some of her clients include CDC, Cigna, GE, Aetna, Cleveland Clinic, CVS etc. She applies the fusion of her clinical expertise, public health knowledge, and data insights in her work.',
	'presenter-PhilRoss-bio'           : 'Philip Ross is an artist, inventor, and scholar whose internationally awarded and exhibited research is focused on biomaterial design and life support technologies. Philip’s innovations in mycelium engineering are globally recognized as foundational to the invention of mycotecture, the practice of building with mycelium. Author of a pending patent on mycelium process engineering, Philip leads MycoWorks’s design and technological research from his comprehensive understanding of applied engineering within living systems.',
	'presenter-RinatSherzer-bio'       : "Passionate multidisciplinary entrepreneur. A strategic product marketing visionary, building ventures at the intersection of tech, design & social good Rinat is an expert in creating human centered platforms. She led and globally launched award-winning products and is behind the flag product of MediaMind (currently Sizmek), one of Israel’s most successful exits to time. She founded three ventures aligned with her vision: 'It Makes Sense', 'Of Course' and 'navlab'. Holds a Bachelor in Biotechnology Engineering from Ben-Gurion University, Israel and a MFA - Design for Social Innovation from the School of Visual Arts, NYC.",
	'presenter-RobertArens-bio'        : "Robert Arens has a diverse background that blends architecture with landscape architecture, technology with design, and professional activity with teaching. His grant-supported projects include the development of rapidly-deployed emergency shelters and the reintroduction of low-impact building methods into US construction practices. His current research focus is legacy cities, particularly the working-class neighborhoods of Detroit where residents who have little access to political power or economic resources manage to survive, resist, adapt and gain access to power through creative and radical acts of urbanism. Robert is a professor of architecture at Cal Poly San Luis Obispo.",
	'presenter-RyanMurphy-bio'         : "Ryan Murphy is a New York based designer interested in how creativity can empower leaders in making bold business and policy decisions. He is currently a designer at SYPartners and has worked with the World Economic Forum and Microsoft's Technology Policy Group, as well as at the forefront of the STEM to STEAM initiative. Ryan received a Red Dot Award  and was recognized by 89Plus as a prominent young artist born after 1989.",
	'presenter-SabrinaDorsainvil-bio'  : 'Sabrina Dorsainvil is a Boston-based designer and illustrator whose work ranges from playful drawings to the development of strategic, human centered design solutions used to address complex issues such as housing and healthcare. She is fascinated by human interaction, and has worked with community-based organizations, large institutions, and on international projects. Currently, she serves the City of Boston as a program manager and civic designer with the New Urban Mechanics.',
	'presenter-SamanthaDempsey-bio'    : 'Samantha is a Senior Service Designer at the Hennepin County Medical Center in Minneapolis. She blends human-centered design, narrative design, and visual storytelling to create positive health outcomes and experiences for patients and staff. Her work focuses on co-designing with underserved populations and improving communication between providers and patients. When she is not designing for safety net hospitals, she enjoys embroidering patterns of bacteria onto household objects.',
	'presenter-SaraMamo-bio'           : 'Sara Mamo is an audiologist and Assistant Professor at the University of Massachusetts Amherst. Her research focuses on improving access to affordable hearing health care for older adults with untreated hearing loss. She is especially interested in developing strategies that address the unique communication and behavioral challenges faced by families experiencing dementia and age-related hearing loss. Over the past year, she has collaborated with the MICA Center for Social Design to develop an engaging, community-delivered hearing care intervention for low-income older adults in Baltimore City.',
	'presenter-SarahRoss-bio'          : 'Sarah Ross is an artist who works in sculpture, video and photo. Her projects use narrative and the body to address spatial concerns as they relate to access, class, anxiety and activism. Sarah also works collaboratively on projects such as Regional Relationships, Chicago Justice Torture Memorials, and Prison and Neighborhood Arts Project. She teaches at SAIC and has co-curated multiple exhibitions and displayed in venues including the Armory, Gallery 727 and PS122.',
	'presenter-StefanoBloch-bio'       : 'Stefano Bloch is a Presidential Diversity Research Associate in Urban Studies at Brown University and an urban geographer specializing in socio-spatial theory, cultural criminology, subcultures, race and identity. He was an Andrew W. Mellon Postdoctoral Fellow in the Humanities from 2013-2015 and is currently completing a book on subcultural identity and urbanism with University of Chicago Press.',
	'presenter-StephanieCaress-bio'    : 'Stephanie Caress is the Innovation Project Associate for the City of Providence, focusing on streamlining City services, promoting entrepreneurship, and enhancing citizen engagement through better communication. This includes developing community engagement modules to generate new ideas and pilot process to solve cross-cutting problems that resonate across all demographics. She also is engaged in many community boards and committees, organizing events for the arts, culture, and entrepreneurial sectors. Her passion lies in collaborating with the creative community to help maintain and promote the vibrant and diverse arts scene in Providence.',
	'presenter-TadHirsch-bio'          : 'Tad Hirsch is Associate Professor of Interaction Design at the University of Washington, and director of the Public Practice Studio, a multidisciplinary, public-interest design group. He previously worked at Intel Labs and Motorola, and has taught at the Rhode Island School of Design and Carnegie Mellon University. Tad is also a founding member of the Institute for Applied Autonomy, an internationally-recognized art/technology/activism collective. He holds PhD and MSc degrees in Media Arts and Sciences from the MIT Media Lab, and an MDes in Interaction Design from Carnegie Mellon University.',
	'presenter-TaylorAlarcon-bio'      : 'Taylor is a senior undergraduate at Brown University. Project Leader of Brown STEAM, Taylor is double concentrating in Applied Mathematics and Philosophy, with interests in using both left and right sides of the brain to build and carry out innovative solutions/ideas that have a substantial impact on society. Outside of STEAM, Taylor is heavily involved in various mentorship and social justice activities on campus.',
	'presenter-TegaBrain-bio'          : 'Tega Brain is an Australian born artist and environmental engineer whose eccentric engineering intersects art, ecology & engineering. Her work has been exhibited worldwide and she is currently a fellow with the Processing Foundation. Tega is an Assistant Professor of New Media at SUNY Purchase and works with the School for Poetic Computation. She has been artist in residence at Eyebeam Art and Technology Center in New York City and the Environmental Health Clinic.',
	'presenter-ThatcherBean-bio'       : 'Thatcher Bean is the Advocacy and Media Producer for MASS Design Group. He joined in 2013 to document the construction and use of MASS Design Group’s health infrastructure in Rwanda. The resulting videos accompanied Alan Rick’s TED talk on how buildings can heal communities. Since then he has worked with MASS as a media producer to explore how video can be used as a unique tool to assess and convey the impact of our built environments. Thatcher obtained a BFA from the University of Colorado film studies program.',
	'presenter-ThomasThwaites-bio'     : 'Thomas Thwaites is a designer exhibited frequently and internationally. His works explore economic, philosophical or techno-social topics across subjects including biology, economics, philosophy, and materials science. He earned an MA in Design Interaction from Royal College of Art and his first book, “The Toaster Project”, was published by Princeton Architectural Press to critical acclaim. It has now been translated into Japanese and Korean editions and was acquired by the Victoria & Albert Museum for their permanent collection. His second book, about his attempt to become a goat, was published in May 2016, and is being translated into Norwegian and Korean.',
	'presenter-VirgilWong-bio'         : 'Virgil Wong (RISD ‘95) creates art and technologies to transform human health. As CEO of Medical Avatar LLC, he has pioneered medical “time travel” visualizations that have dramatically reduced the incidence of diabetes and heart disease. He is currently Executive Director of Creative Services at Element Solutions, a customer engagement company with technological expertise in healthcare and other industries.Virgil has also exhibited his interactive art installations in museums around the world.',

	'presenter-AmandaPhingbodhipakkiya-bio'  : 'Amanda Phingbodhipakkiya is a Creative Director and Design Strategist. A graduate of Columbia and Pratt, Amanda brings design and science together through initiatives like The Leading Strand and projects like Beyond Curie in addition to her speaking engagements at institutions like TED, Unilever, Microsoft, and Mt. Sinai.',
	'presenter-AnnuMatthew-bio'        : "Annu Palakunnathu Matthew's photo-based artwork explores re-looking at cultural histories, identity, and memory. Matthew's recent solo exhibitions include the Royal Ontario Museum, Nuit Blanche Toronto, and sepiaEYE, nyc. Fellowships include a Fulbright, MacColl Johnson and Rhode Island State Council of the Arts fellowships. Matthew is Professor of Art at the University of Rhode Island.",
	'presenter-BarbaraWeinreich-bio'   : 'Barbara Laskey Weinreich is an architect and was a founding Principal at MNA (www.mnarch.com), a leader in retail design. Clients included Ralph Lauren, Patagonia, West Elm, Bergdorf Goodman, Michael Kors and Coach. Barbara is an adjunct professor at the Pratt Institute and The New York School of Interior Design, currently teaching in both the undergraduate and MFA programs. She has a BA, Magna Cum Laude in Art History from Brown University and a Master’s Degree in Architecture from Columbia University.',
	'presenter-BethRattner-bio'		   : 'Beth Rattner is the Executive Director of the Biomimicry Institute, a non-profit working with academia, industry, and other NGOs to look to nature for design guidance. She is a frequent public speaker on how biomimetic design in products, cities, and agriculture can restore our economy and ecosystem, while spurring new levels of health and social equity. The Institute provides the tools and platforms to democratize the practice of nature-inspired design. <br/> Prior to this position, Beth worked with William McDonough and Michael Braungart on The Upcycle, the sequel to Cradle to Cradle, before she helped co-found the Cradle to Cradle Products Innovation Institute and became its first Executive Director. In that role she often met with and advised companies looking to transform their product lines into sustainable, and ultimately “circular” products and services. Cradle to Cradle emphasizes material health, meaning identifying and then removing toxic substances. Oftentimes the companies would be left with no viable commercial options. It was then that Beth realized biomimicry could offer a much-needed new design paradigm.<br/>Her background has long been in supporting innovation, first as an attorney and business development manager and then consultant to Fortune 100 companies. As managing director for Blu Skye Sustainability Consultants, Beth led teams advising sustainability strategies for one of the top three largest (market value) tech companies and one of the largest hotel chains worldwide. Her tech background began at America Online in the late 1990’s and then continued to Hewlett Packard, where she helped lead their Emerging Market Solutions (EMS) group. EMS focused on providing sustainable technology solutions to those who earn less than $2 a day. The team launched HP’s first multi-user, daisy-chained computer for poorly funded schools and a solar-powered printer, providing microfinance opportunities for women who could bring photographs to remote villages for the very first time. <br/>Beth lives in Marin County, just north of the Golden Gate bridge, where she finds daily inspiration from the redwood trees and oaks and the innumerable other creatures that live amongst them.',

	'presenter-AlanHarlam-link'         : 'https://www.brown.edu/academics/college/special-programs/public-service/social-innovation-initiative/index.php?q=alan-harlam',
	'presenter-AllenPenniman-link'      : 'http://allenpenniman.com/',
	'presenter-AndrewScanlan-link'      : 'https://www.linkedin.com/in/jamesandrewscanlan',
	'presenter-AndrewMartinez-link'     : '#',
	'presenter-AndyLaw-link'            : 'https://www.linkedin.com/in/andrewjlaw',
	'presenter-AugustLehrecke-link'     : 'http://pneu.haus',
	'presenter-AzminaAlimohd-link'      : 'https://azminaalimohd.carbonmade.com',
	'presenter-BeckySlogeris-link'      : '#',
	'presenter-BoriFeher-link'          : 'http://cloudfactory.mome.hu/?l=eng',
	'presenter-CarlyWais-link'          : '#',
	'presenter-CarolineMcAndrews-link'  : 'https://www.linkedin.com/in/carolinebmcandrews',
	'presenter-CesarHidalgo-link'       : 'http://www.chidalgo.com/',
	'presenter-ChrisNovello-link'       : 'http://chrisnovello.com/',
	'presenter-ChristinaAgapakis-link'  : 'http://agapakis.com/',
	'presenter-CraigDykers-link'        : 'http://snohetta.com/',
	'presenter-CynthiaPoon-link'        : 'http://www.incrementstudios.com/',
	'presenter-DanaChisnel-link'        : 'http://civicdesign.org/',
	'presenter-DanSheehan-link'         : 'http://www.humblepiepvd.com',
	'presenter-DavidRojas-Leon-link'    : 'http://www.davidrojasleon.com/',
	'presenter-DhairyaPujara-link'      : 'http://y-center.org/dhairyapujara/',
	'presenter-ElizabethWilliams-link'  : '#',
	'presenter-EllenSu-link'            : 'http://www.wellinks.com/',
	'presenter-EmilyHerrick-link'       : 'https://emilyherrickdesign.com/index.html',
	'presenter-EmilyKao-link'           : 'http://www.emoolymoo.com/',
	'presenter-GenaWirth-link'          : 'http://www.scapestudio.com/',
	'presenter-HannahChung-link'        : 'http://www.sproutel.com/',
	'presenter-IanGonsher-link'         : 'http://gonsherdesign.com/',
	'presenter-IanAldenRussell-link'    : '#',
	'presenter-IlonaGaynor-link'        : 'http://www.ilonagaynor.co.uk',
	'presenter-ImranHafiz-link'         : 'https://www.linkedin.com/in/imhafiz',
	'presenter-IngridBurrington-link'   : '#',
	'presenter-JaminWarren-link'        : 'https://killscreen.com/author/jamin-warren/',
	'presenter-JeremyJoachim-link'      : 'http://www.jeremyjoachim.com/',
	'presenter-JessSuttner-link'        : 'http://itmakessense.org/',
	'presenter-JuhanSonin-link'         : 'http://www.linkedin.com/in/juhansonin',
	'presenter-KatieCafaro-link'        : 'http://portfolios.risd.edu/KatieCafaro',
	'presenter-KaylaIngram-link'        : 'https://www.linkedin.com/in/kaylajingram',
	'presenter-KellanHays-link'         : 'http://www.autodesk.com',
	'presenter-KenjiEndo-link'          : 'http://www.ckendo.com/',
	'presenter-KursatOzenc-link'        : 'http://kursatozenc.com',
	'presenter-LaurenGardner-link'      : 'http://lauren-g.com',
	'presenter-LeahChung-link'          : 'http://leahericachung.com/',
	'presenter-LelandKirshen-link'      : 'https://www.linkedin.com/in/leland-kirshen-01b3bb8b',
	'presenter-LeslieFontana-link'      : 'https://www.linkedin.com/in/leslie-fontana-b0abb26',
	'presenter-LeviBedall-link'         : '#',
	'presenter-LisaRaiola-link'         : 'https://makefoodyourbusiness.org',
	'presenter-ManoloAmpudia-link'      : '',
	'presenter-MariaNavia-link'         : 'https://www.linkedin.com/in/mpaulanavia/',
	'presenter-MattMuller-link'         : 'http://pneu.haus',
	'presenter-MaxFowler-link'          : 'http://mfowler.info/',
	'presenter-MeganKelly-link'         : 'http://frnbrown.blogspot.com',
	'presenter-MikeWeikert-link'        : '#',
	'presenter-MikhaelaDietch-link'     : 'http://mikhaeladietch.com/',
	'presenter-NateStorring-link'       : 'http://www.nathanstorring.com/',
	'presenter-OlgaElizarova-link'      : 'http://madpow.com/',
	'presenter-PhilRoss-link'           : 'http://www.mycoworks.com/team/philip-ross/',
	'presenter-RinatSherzer-link'       : 'http://itmakessense.org/',
	'presenter-RobertArens-link'        : 'http://architecture.calpoly.edu/faculty/arens',
	'presenter-RyanMurphy-link'         : 'http://r-murphy.com',
	'presenter-SabrinaDorsainvil-link'  : 'http://newurbanmechanics.org',
	'presenter-SamanthaDempsey-link'    : 'http://www.samanthadempsey.com/',
	'presenter-SaraMamo-link'           : '#',
	'presenter-SarahRoss-link'          : 'http://www.insecurespaces.net/',
	'presenter-StefanoBloch-link'       : 'https://www.linkedin.com/in/stefano-bloch-51842334',
	'presenter-StephanieCaress-link'    : '#',
	'presenter-TadHirsch-link'          : 'http://publicpractice.org/wp/',
	'presenter-TaylorAlarcon-link'      : 'http://www.philosomatician.com/',
	'presenter-TegaBrain-link'          : 'http://tegabrain.com/',
	'presenter-ThatcherBean-link'       : 'http://massdesigngroup.org/',
	'presenter-ThomasThwaites-link'     : 'http://www.thomasthwaites.com/',
	'presenter-VirgilWong-link'         : 'http://virgilwong.com',

	'presenter-AmandaPhingbodhipakkiya-link' : 'http://alonglastname.com',
	'presenter-BarbaraWeinreich-link'	: 'http://www.mnarch.com',
	'presenter-BethRattner-link'		: '#',

	'presenter-AlexandraGinsberg-bio' : 'Alexandra Daisy Ginsberg is an artist and designer, developing experimental approaches to imagine alternative values around design, science, and technology. Lead author of Synthetic Aesthetics: Investigating Synthetic Biology’s Designs on Nature (MIT Press, 2014), her PhD research, Better, at London\'s Royal College of Art (expected 2017), looks into the powerful social imaginary of “better”. Daisy received the World Technology Award (Design) 2011, the first London Design Medal for Emerging Talent 2012, and her work has been twice nominated for Designs of The Year (2011, 2015).',

	'presenter-BillLucas-name' : 'Bill Lucas',
	'presenter-BillLucas-img' : 'url(../../images/presenters2017/BillLucas.jpg)',
	'presenter-BillLucas-bio' : 'Bill Lucas is an advocate of universal design literacy. He is the chief architect of LUMA’s System of Innovation, and co-author of “Innovating for People.” Bill designs learning experiences for K-12 and Higher Ed—including Professional Development for educators and Project-Based Learning for students. Previously, Bill served as a Professional Practice Fellow at MAYA Design. Bill holds a B.S. in Graphic Design from the University of Cincinnati—graduating Summa Cum Laude from the College of Design, Architecture, Art and Planning.',
	'presenter-BillLucas-link' : 'https://www.luma-institute.com',

	'presenter-CaitlinSilverstein-name' : 'Caitlin Silverstein',
	'presenter-CaitlinSilverstein-img' : 'url(../../images/presenters2017/CaitlinSilverstein.jpg)',
	'presenter-CaitlinSilverstein-bio' : 'Caitlin Silverstein partners with organizations to develop cultures of innovation. She is inspired when people and teams apply human-centered design to solve old challenges in new ways. Previously, Caitlin spent seven years at Continuum, and throughout her career, Caitlin has remained passionate about sharing human-centered design with all organizations and believes that the methodology is relevant and applicable across all industries. Caitlin earned her B.A. in Economics from Middlebury College, returning annually to teach in the college’s MiddCORE program.',
	'presenter-CaitlinSilverstein-link' : 'https://www.luma-institute.com',

	'presenter-CynthiaSmith-name' : 'Cynthia Smith',
	'presenter-CynthiaSmith-img' : 'url(../../images/presenters2017/CynthiaSmith.jpg)',
	'presenter-CynthiaSmith-bio' : 'Cynthia E. Smith serves as Cooper Hewitt, Smithsonian Design Museum’s Curator of Socially Responsible Design. Trained as an industrial designer; for more than a decade she led multidisciplinary design and planning projects for cultural institutions; and after earning a graduate degree from Harvard’s Kennedy School of Government joined Cooper Hewitt where she integrates her work experience with her advocacy on human rights and social justice issues. She co-authored "The Politics of Genocide: U.S. Rhetoric vs. Inaction in Darfur" for the Kennedy School Review; curated "By the People: Designing a Better America" (2016); co-organized the Social Impact Design Summit and white paper with the National Endowment for the Arts; curated "Design with the Other 90%: CITIES" at the United Nations headquarters (2011); co-curated the "Design Triennial: Why Design Now?" (2010); curated the groundbreaking "Design for the Other 90%" exhibition (2007). Named a “20/20 New Pioneer” by Icon design magazine; she serves on numerous international design juries, including the current Resilient by Design Bay Area Challenge; is the Smithsonian expert on Inclusive Cities for the World Economic Forum’s Transformation Map; and lectures widely on socially responsible design.',
	'presenter-CynthiaSmith-link' : '#',

	'presenter-Ekene-name' : 'Ekene Ijeoma',
	'presenter-Ekene-img' : 'url(../../images/presenters2017/Ekene.jpg)',
	'presenter-Ekene-bio' : 'Ekene Ijeoma is an interdisciplinary artist and designer exploring the intersections of social issues, data studies and life experiences through websites, apps, installations, and performances. Commissioners of his work include: Annenberg Space for Photography (Los Angeles), Neuberger Museum of Art (Purchase, NY), Storefront for Art and Architecture (New York), Pratt Manhattan Gallery (New York), Panorama Festival (New York), Google Creative Lab (New York) and American Institute of Graphic Arts. His work has been exhibited at galleries and museums including Design Museum (London), Istanbul Design Biennial, Annenberg Space for Photography, Neuberger Museum of Art, and Storefront for Art and Architecture. Ekene was awarded fellowships and residencies from Kennedy Center (Citizen Artist, 2017/2018), New Museum (Ideas City, 2016), New York Foundation for the Arts (Architecture/Environmental Structures/Design, 2016/2017), California College of the Arts (Vibrant Cities, 2017), Santa Fe Art Institute (Equal Justice, 2017/2018), New Lab/Simons Foundation (Science Sandbox, 2017), Urban Design Forum (Forefront, 2017), and Fabrica (2014). He was featured on the cover of GDUSA\'s People to Watch "who embody the spirit of the creative community", named Adweek\'s Creative 100 "visual artist whose imagination and intellect will inspire you" and also GOOD\'s GOOD 100 "tackling pressing global issues." His work has also been featured in MoMA, Huffington Post, The Atlantic, Le Monde, Corriere della Sera, Internazionale, Vice, Fusion, WIRED, Fast Company, Dezeen, Designboom, Domus, Hyperallergic and Artsy. He’s appeared on TV and radio shows including Fox 4 News, W Radio and Canadian Broadcasting Company (CBC) Radio. Ekene has a BS in Information Technology from Rochester Institute of Technology and an MA in Interaction Design from Domus Academy. He was a lecturer at The New School, guest lecturer at Columbia, New York University, University of San Francisco, The New School and School of Visual Arts (SVA), guest critic at Yale and SVA, and visiting artist at Virginia Commonwealth University and School for Poetic Computation. He was recently appointed as a Mitchell Visiting Professor in Architecture, Interior Architecture and Designed Objects (AIADO) at the School of Art Institute of Chicago (SAIC). A first generation Nigerian-American, he was born in Fort Worth, Texas and lives and works in New York City.',
	'presenter-Ekene-link' : '#',

	'presenter-GabrielleBufrem-name' : 'Gabrielle Bufrem',
	'presenter-GabrielleBufrem-img' : 'url(../../images/presenters2017/GabrielleBufrem.jpg)',
	'presenter-GabrielleBufrem-bio' : 'Gabrielle Bufrem is a Product Manager at Pivotal Labs in Paris. She works with a range of clients from large corporations to start-ups in order to build user-centered products. She works at the intersection of design, technology, and business ensuring that the products she manages provide value to both users and the business. Prior to Pivotal, she worked as a Product Manager in ed-tech for Education First, an international education company. Gabrielle earned a B.A. from Brown University in International Relations.',
	'presenter-GabrielleBufrem-link' : 'https://pivotal.io/labs',

	'presenter-IngridLange-name' : 'Ingrid Lange',
	'presenter-IngridLange-img' : 'url(../../images/presenters2017/IngridLange.jpg)',
	'presenter-IngridLange-bio' : 'Ingrid Lange is a Design Researcher at IBM Watson Health and design consultant for IBM Research in Cambridge, MA. She loves learning about learning and designing for it. Chat with her about education, discursive design, and growing up in the sweet Midwest.',
	'presenter-IngridLange-link' : 'http://www.ingridlange.com/',

	'presenter-JamesAuger-name' : 'James Auger',
	'presenter-JamesAuger-img' : 'url(../../images/presenters2017/JamesAuger.jpg)',
	'presenter-JamesAuger-bio' : 'James Auger is an associate professor at Madeira Interactive Technologies Institute (M-ITI) in Portugal.  His current research explores the potential of the Island as an experimental living laboratory through a combination of fictional, factual and functional multi-scale energy-related proposals and projects. This work was recently awarded the Cultural Innovation International Prize by the Centre of Contemporary Culture of Barcelona (CCCB).<br/>After studying Design Products (MA) at the Royal College of Art  James moved to Dublin to conduct research at Media Lab Europe (MLE) exploring the theme of human communication as mediated by technology. After MLE he worked in Tokyo as guest designer at the Issey Miyake Design Studio developing new concepts for mobile telephones. Between 2005 and 2015 James was part of the critically acclaimed Design Interactions department at the RCA, teaching on the MA programme and continuing his development of critical and speculative approaches to design and technology, completing his PhD on the subject in 2012. Running parallel to his academic work James is partner in the speculative design practice Auger-Loizeau, a collaboration founded in 2000. Auger-Loizeau projects have been published and exhibited internationally, including MoMA, New York; 21_21, Tokyo; The Science Museum, London; The National Museum of China, Beijing and Ars Electronica, Linz. Their work is in the permanent collection at MoMA. ',
	'presenter-JamesAuger-link' : '#',

	'presenter-JohnZelek-name' : 'John Zelek',
	'presenter-JohnZelek-img' : 'url(../../images/presenters2017/JohnZelek.jpg)',
	'presenter-JohnZelek-bio' : 'John Zelek is the Senior Creative at Soylent, a company working to provide better access to complete nutrition through innovative (and sometimes controversial) new food products. After studying industrial design, he now works on a much broader range of creative projects for Soylent, bringing design solutions to marketing challenges. He recently led the design execution on the packaging revamp for the Soylent Drink line.',
	'presenter-JohnZelek-link' : 'http://johnzelek.com',

	'presenter-KitMcDonnell-name' : 'Kit McDonnell',
	'presenter-KitMcDonnell-img' : 'url(../../images/presenters2017/KitMcDonnell.jpg)',
	'presenter-KitMcDonnell-bio' : 'Kit McDonnell is on the Creative Team at Ginkgo Bioworks. At Tufts University (BS Biology), she founded TEDxTufts and the Tufts Venture Lab. She’s researched myriad organisms (notably, cheese and ant microbiomes, Neotropical avian malaria, and pu-erh tea). Since catching the biodesign bug abroad in Hong Kong, she hasn’t looked back.',
	'presenter-KitMcDonnell-link' : '#',

	'presenter-KristenChin-name' : 'Kristen Chin',
	'presenter-KristenChin-img' : 'url(../../images/presenters2017/KristenChin.jpg)',
	'presenter-KristenChin-bio' : 'Kristen is a social impact designer and community collaborator working as an Enterprise Rose Architectural Fellow with Urban Edge and Jamaica Plain Neighborhood Development Corporation in Boston. Previously, she managed projects related to sustainability and post-Sandy recovery at the Pratt Center for Community Development in New York City. She has worked with community-based organizations, policymakers, and government agencies to advocate for more equitable cities. Kristen holds a Master of Architecture from Parsons School of Design and earned her undergraduate degree from Brown University.',
	'presenter-KristenChin-link' : '#',

	'presenter-KrystalSarcone-name' : 'Krystal Sarcone',
	'presenter-KrystalSarcone-img' : 'url(../../images/presenters2017/KrystalSarcone.jpg)',
	'presenter-KrystalSarcone-bio' : 'Known to dabble in a variety of projects across industries and in the most multi-disciplinary and cross-brain way possible, Krystal’s academic interests pull from her previous clinical nonprofit work. One main passion of hers is to create apparel that features universal design elements and is adaptive to more diverse needs.',
	'presenter-KrystalSarcone-link' : '#',

	'presenter-KyraPerry-name' : 'Kyra Perry',
	'presenter-KyraPerry-img' : 'url(../../images/presenters2017/KyraPerry.jpg)',
	'presenter-KyraPerry-bio' : 'I am a sophomore from Atlanta, Georgia planning on concentrating in Business Economics and Urban Studies at Brown University. Growing up in Georgia, I developed a love and appreciation for nature and sustainability. I spend most of my time outside, and I cannot sit in one place for too long. As co-President of Brown STEAM, I facilitate communications between disparate fields of thought, because I believe STEM fields, art, and humanities all benefit from each other.',
	'presenter-KyraPerry-link' : 'http://steamwith.us/BrownSTEAM.html',

	'presenter-LeoSelvaggio-name' : 'Leo Selvaggio',
	'presenter-LeoSelvaggio-img' : 'url(../../images/presenters2017/LeoSelvaggio.jpg)',
	'presenter-LeoSelvaggio-bio' : 'Leonardo Selvaggio is an interdisciplinary artist whose work examines the intanglement of identity and technology. He has shown work internationally in France, Canada, Amsterdam, and Switzerland as well as exhibiting broadly in the United States. Selvaggio’s academic work has been published in the International Journal for Performance Arts and Digital Media and as part of” Behind the Smart World - Saving, Deleting and Resurfacing Data” published by LAFKON. He holds a BFA from Rutgers University and an MFA from Columbia College’s Interdisciplinary Arts program. For more information visit www.leoselvaggio.com',
	'presenter-LeoSelvaggio-link' : 'http://www.LeoSelvaggio.com',

	'presenter-MandiCai-name' : 'Mandi Cai',
	'presenter-MandiCai-img' : 'url(../../images/presenters2017/MandiCai.jpg)',
	'presenter-MandiCai-bio' : 'Mandi merged cognitive neuroscience and design during her studies at Brown. She\'s now working in interaction design at BioBright, building tools to augment the scientist in the laboratory. Talk to her about Elon Musk, augmented reality, Stranger Things, and dogs.',
	'presenter-MandiCai-link' : '#',

	'presenter-MartinKeen-name' : 'Martin Keen',
	'presenter-MartinKeen-img' : 'url(../../images/presenters2017/MartinKeen.jpg)',
	'presenter-MartinKeen-bio' : 'As a product designer, brand creator, and serial entrepreneur, Martin Keen has spent his career creating and building ideas born out of need. After founding the world-renowned outdoor brand KEEN Footwear in 1999, Martin was inspired to design a seat that could keep him physically engaged and comfortable while he worked. Twelve years later, Focal Upright was born.',
	'presenter-MartinKeen-link' : 'https://www.focalupright.com/',

	'presenter-MeiHsieh-name' : 'Mei Hsieh',
	'presenter-MeiHsieh-img' : 'url(../../images/presenters2017/MeiHsieh.jpg)',
	'presenter-MeiHsieh-bio' : 'Mei is a UX designer with a passion for addressing complex problems by creating sustainable systems, effective services, and thoughtful experiences. She has worked with clients like the Gates Foundation, Dr. Reddy’s, Intuitive Surgical and Physio to develop meaningful solutions for their users. Her passion for healthcare and education have led her to work on a variety of projects including interface design for a family of paramedic devices; UX design for devices that assist robotic surgery in the operating room; field research for breast cancer patients in India; and designing an online community platform for U.S. K-12 teachers to share curriculum and resources. Mei graduated from the University of Cincinnati, where she earned a Bachelor’s degree in Industrial Design',
	'presenter-MeiHsieh-link' : '#',

	'presenter-RosaPark-name' : 'Rosa Park',
	'presenter-RosaPark-img' : 'url(../../images/presenters2017/RosaPark.jpg)',
	'presenter-RosaPark-bio' : 'Officially, Rosa is an Industrial Design student from RISD. Unofficially, she is someone who involves herself in many multidisciplinary design projects at a time. Originally from Panama, she has been involved in projects ranging from medicine to food and urban design abroad. Nonetheless, her diverse interests are strung together by two common threads – a curious mindset and a designer’s mind. She currently leads the RISD/Brown Design for America organization, where she teaches others to create social impact through design.',
	'presenter-RosaPark-link' : '#',

	'presenter-SherylCababa-name' : 'Sheryl Cababa',
	'presenter-SherylCababa-img' : 'url(../../images/presenters2017/SherylCababa.jpg)',
	'presenter-SherylCababa-bio' : 'With one foot planted in design research and strategy, and another in interaction design, Sheryl is a multi-disciplinary design director with the unique ability to see both the forest as well as the trees. Prior to joining Artefact, she worked at frog and Adaptive Path, as well as technology companies Philips and Microsoft. She has experience leading projects for clients across industries from personal finance to robotic surgery systems. With her design weapon of choice (the Paper Mate Flair) handy at all times, she has also helped other designers spark their creativity by leading workshops in sketching, interaction design, and design research methods.',
	'presenter-SherylCababa-link' : '#',

	'presenter-TinaGong-name' : 'Tina Gong',
	'presenter-TinaGong-img' : 'url(../../images/presenters2017/TinaGong.jpg)',
	'presenter-TinaGong-bio' : 'Tina is a self-taught illustrator, designer and front-end developer. She graduated from NYU with a degree in linguistics, and has been interested in the intersections between the structures of language, symbolism, art, and design for as long as she could remember. When she was in college, she started creating HappyPlayTime, a sex-education app focused on female masturbation. She is also the creator of Labyrinthos Academy, a series of mystical apps and decks that teach tarot for developing self-understanding. Awkward and introverted, she does not usually venture out of her secret hideout / studio, but will occasionally do so to pet alpacas and go to cool things, like this!',
	'presenter-TinaGong-link' : '#',

	'presenter-WilliamBarry-name' : 'William Barry',
	'presenter-WilliamBarry-img' : 'url(../../images/presenters2017/WilliamBarry.jpg)',
	'presenter-WilliamBarry-bio' : 'William Barry is a student studying Graphic Design at Suffolk University\'s New England School of Art and Design. As a former UI/UX Designer at BioBright, he established the look and feel for BioBright\'s software applications as well as implemented a new brand identity for the company. He specializes in prototyping, conceptual development & ideation, illustration, and app design, and hopes to use these skills across a variety of different fields and industries.',
	'presenter-WilliamBarry-link' : 'http://www.mrwilliambarry.com',

	'presenter-BarbaraStehle-name' : 'Barbara Stehle',
	'presenter-BarbaraStehle-img' : 'url(../../images/presenters2017/BarbaraStehle.png)',
	'presenter-BarbaraStehle-bio' : 'Barbara Stehle received her Doctorate in Contemporary Art History from the Sorbonne in Paris. She has worked for several museums including the Pompidou Center. Her Ted x talk addressed architecture as a mean for human investigations. Based in NYC, she founded Art Intelligentsia, for which she curates, writes and lectures on the visual arts and architecture.  Her research on Max Beckmann has been published in major exhibition catalogues. A passionate historian of modernism, she is thoroughly convinced of the necessity of postmodernism.',
	'presenter-BarbaraStehle-link' : 'http://www.artintelligentsia.com/',

	'presenter-DoremyDiatta-name' : 'Doremy Diatta',
	'presenter-DoremyDiatta-img' : 'url(../../images/presenters2017/DoremyDiatta.png)',
	'presenter-DoremyDiatta-bio' : 'Doremy Diatta is co-founder of Matter–Mind Studio, a consultancy run by three women based in New York City. We do research, strategy, and design and specialize in developing Emotion-Centered Design methodologies and tools. We work with people to articulate their inner needs -- to help organizations, institutions, and companies to take better care.',
	'presenter-DoremyDiatta-link' : '#',

	'presenter-Emilio-name' : 'Emilio Martinez Poppe',
	'presenter-Emilio-img' : 'url(../../images/presenters2017/Emilio.png)',
	'presenter-Emilio-bio' : 'Emilio Martinez Poppe is an artist, designer, and educator based in New York. Their work includes video performance, websites, essays, garment design, place and research based collaborative projects. Emilio’s practices and collaborations have been supported by the Laundromat Project New Museum, Cooper Union, SOMA, and the University of Massachusetts Amherst. Their work has been presented at Cornell University, MICA, Cooper Union, Creative Time, Framer Framed, Side Room, and Vlaams Cultuurhuis de Brakke Grond. Emilio is currently a member of the collective BFAMFAPhD and a Create Change fellow with The Laundromat Project.',
	'presenter-Emilio-link' : '#',

	'presenter-JohnPipkin-name' : 'John Pipkin',
	'presenter-JohnPipkin-img' : 'url(../../images/presenters2017/JohnPipkin.png)',
	'presenter-JohnPipkin-bio' : 'John Pipkin teaches creative writing and literature at UT Austin, and he is the author of two novels, Woodsburner and The Blind Astronomer\'s Daughter.  He has received awards from the New York Center for Fiction, the Massachusetts Center for Book, and the Texas Institute of Letters, as well as fellowships from the MacDowell Colony, Yaddo, the Harry Ransom Center, and the Dobie-Paisano Program.  He is currently working on a novel about the Tour de France during World War II.',
	'presenter-JohnPipkin-link' : '#',

	'presenter-JoyceHwang-name' : 'Joyce Hwang',
	'presenter-JoyceHwang-img' : 'url(../../images/presenters2017/JoyceHwang.png)',
	'presenter-JoyceHwang-bio' : 'Joyce Hwang is the Director of Ants of the Prairie, a practice of architectural research and design that focuses on confronting contemporary ecological conditions through creative means, and an Associate Professor of Architecture at the University at Buffalo SUNY. She is a recipient of the Architectural League Emerging Voices Award, the New York Foundation for the Arts (NYFA) Fellowship, and the MacDowell Colony Fellowship, among other awards. She is currently working on a “habitecture” installation in Australia.',
	'presenter-JoyceHwang-link' : '#',

	'presenter-Paolo-name' : 'Paolo Cardini',
	'presenter-Paolo-img' : 'url(../../images/presenters2017/Paolo.png)',
	'presenter-Paolo-bio' : 'Paolo Cardini is Associate Professor in Industrial Design at Rhode Island School of Design. His research work ranges from Critical to Speculative Design with a specific focus on intercultural issues. He consults for various international firms and he is lecturing in conferences and design schools worldwide contributing actively to the field pushing the boundaries of what design can do.',
	'presenter-Paolo-link' : '#',

	'presenter-NickScappaticci-name' : 'Nick Scappaticci',
	'presenter-NickScappaticci-img' : 'url(../../images/presenters2017/NickScappaticci.png)',
	'presenter-NickScappaticci-bio' : 'As Chief Executive Officer, Nick leads Tellart in high-level operational and strategic decisions, while still being involved in details of project development, execution, and troubleshooting. He is responsible for leading a staff of strategists, designers and technologists, and for creating a cohesive cultural environment for Tellart that enables project and career success.<br/>Nick studied Industrial Design at the Rhode Island School of Design (RISD). He is currently a member of the Adjunct Faculty at RISD where he teaches interface design and senior studio.',
	'presenter-NickScappaticci-link' : '#',

	'presenter-StephanieDinkins-name' : 'Stephanie Dinkins',
	'presenter-StephanieDinkins-img' : 'url(../../images/presenters2017/StephanieDinkins.png)',
	'presenter-StephanieDinkins-bio' : 'Stephanie Dinkins is an artist interested in creating platforms for ongoing dialog about artificial intelligence as it intersects race, gender, aging, the proliferation of knowledge(s) and our future histories. She is particularly driven to work with communities of color to develop deep-rooted AI literacy and co-create more equitable artificial intelligence. She is recipient of a 2017 A Blade of Grass Fellowship for Socially Engaged Art and 2018 EYEBEAM Trust Residency. Professor Dinkins teaches digital art and interactive media at Stony Brook University.',
	'presenter-StephanieDinkins-link' : 'http://www.stephaniedinkins.com/'
};

function populateModal(elt) {
	var id = elt.parent().attr('id');
	console.log(id);

	var name = bioInfo[id + '-name'];
	var img = bioInfo[id + '-img'];
	var bio = bioInfo[id + '-bio'];
	var link = bioInfo[id + '-link'];

	var modal = $("#modalPopup");

	modal.find('.personImg').css('background-image', img);
	modal.find('.name').html(name);
	modal.find('.name').attr('href', link);
	modal.find('.bio').html(bio);
}

function populateModalNoLink(elt) {
	var id = elt.parent().attr('id');
	console.log(id);

	var name = bioInfo[id + '-name'];
	var img = bioInfo[id + '-img'];
	var bio = bioInfo[id + '-bio'];
	var link = bioInfo[id + '-link'];

	var modal = $("#modalPopupNoLink");

	modal.find('.personImg').css('background-image', img);
	modal.find('.nameNoLink').html(name);
	modal.find('.nameNoLink').attr('href', link);
	modal.find('.bio').html(bio);
}
``
function clickable(elt) {
	return elt.attr('href') !== '#';
}
